### ISSUE TITLE
Integrate with Android client / iOS feedback

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#66] opened 2020-08-05 13:36 UTC
1. Transaction summary list endpoint (`/v1/safes/<safe-address>/transactions/?next=`):
  - [x] Android integrated https://github.com/gnosis/safe-android/issues/776
  - [x] iOS usable
2. Transaction details endpoint (`/v1/transactions/<transaction_id>`):
 - [x] Android integrated https://github.com/gnosis/safe-android/pull/788
 - [ ] iOS usable

For each of the above tasks it should be checked also with iOS that the returned information is sufficient and can be used by them.

**Comment by jpalvarezl** [comment] 2020-08-17 14:58
Feedback from iOS for the transaction summary list:
- [ ] Regarding the `previous` and `next` links returned by the `Page` of data. Then the TX summary list endpoint takes only as a query param `next`. Which is confusing. Maybe we can change it to `page_url` or something more generic.
- [ ] rename  the  "masterCopy" field in the "Creation" transaction  info to the "implementation"
- [ ] Having type variants for `SettingsChange` instead of having the clients look into `DataDecoded` anyway
- [ ] Some types are missing in the documentation wiki: `TransferDirection`, `Operation`, `DataDecoded`, `Parameter`, `ParamValue`, `DetailedExecutionInfo`

**Comment by jpalvarezl** [comment] 2020-08-19 10:43
After today's 11:30 we concluded that the only change required by Android for the correct rendering of details and list is that we include the `submission_date` of every `confirmation` for which the fix should be implemented by this #116

**Comment by jpalvarezl** [comment] 2020-08-20 09:14
The issue is closed as this task was mainly for monitoring the integration with Android. Additional feedback from iOS would still be appreciated at any point in time.

**Closed by jpalvarezl** 2020-08-20 09:14 UTC
