### ISSUE TITLE
Unexpected new error message when I propose an already executed transaction

### ISSUE THREAD

**Issue by DaniSomoza** [gnosis/safe-client-gateway#752] opened 2021-12-16 16:45 UTC
**Describe the bug**

Hi guys, **I get a different error message when I propose an already executed transaction**:

**To Reproduce**
- Call to the propose transaction endpoint:
```
curl --location --request POST 'https://safe-client.staging.gnosisdev.com/v1/chains/4/transactions/0x4f9BD57BCC68Bf7770429F137922B3afD23d83E7/propose' \
--header 'Content-Type: application/json' \
--data-raw '{
  "to": "0x49d4450977E2c95362C13D3a31a09311E0Ea26A6",
  "value": "0",
  "data": "0xe8dde2320000000000000000000000000000000000000000000000000000000000000000",
  "operation": 0,
  "nonce": "1",
  "safeTxGas": "39557",
  "baseGas": "0",
  "gasPrice": "0",
  "gasToken": "0x0000000000000000000000000000000000000000",
  "refundReceiver": "0x0000000000000000000000000000000000000000",
  "safeTxHash": "0x98798b6d9400b25397e85eb79c444a06f93d153555c1d7fd026176f02055a824",
  "sender": "0x474e5Ded6b5D078163BFB8F6dBa355C3aA5478C8",
  "origin": null
}
'
```
- Actual Result:
```
{
    "code": 1337,
    "message": "{\"nonFieldErrors\":[\"Contract-transaction-hash=0xdf2c4db07ee705e94135d92f835cc241b1d4c20e10d481a4e445265851448cb3 does not match provided contract-tx-hash=0x98798b6d9400b25397e85eb79c444a06f93d153555c1d7fd026176f02055a824\"]}"
}
```

**Expected behavior**

```
'1337: {"nonFieldErrors":["Tx with safe-tx-hash=0x98798b6d9400b25397e85eb79c444a06f93d153555c1d7fd026176f02055a824 for safe=0x4f9BD57BCC68Bf7770429F137922B3afD23d83E7 was already executed in tx-hash=0x1baa941b8696ff3b0a8831f11da243a02f028122b6298ee61e3a1c0d5eeb171a"]}',
```

**Environment:**
 - Staging
 - Rinkeby chain
 - Safe used: https://gnosis-safe.io/app/rin:0x4f9BD57BCC68Bf7770429F137922B3afD23d83E7/transactions/history
 - Tx Already executed: 0x1baa941b8696ff3b0a8831f11da243a02f028122b6298ee61e3a1c0d5eeb171a
 - Nonce: 1

**Additional context**
In the new weird error is present: `0xdf2c4db07ee705e94135d92f835cc241b1d4c20e10d481a4e445265851448cb3`
But I can not find anything about that in Etherscan: https://etherscan.io/tx/0xdf2c4db07ee705e94135d92f835cc241b1d4c20e10d481a4e445265851448cb3

![Captura de pantalla 2021-12-16 a las 17 34 03](https://user-images.githubusercontent.com/26763673/146412925-d46859af-3d8c-4735-96bb-7630864506d9.png)
![Captura de pantalla 2021-12-16 a las 17 35 02](https://user-images.githubusercontent.com/26763673/146412934-371a8e76-4037-46e8-a5dc-b682d067c4ce.png)

**Comment by rmeissner** [comment] 2021-12-17 08:17
Duplicate of https://github.com/gnosis/safe-client-gateway/issues/745

**Closed by rmeissner** 2021-12-17 08:17 UTC
Labels: bug
